### PR TITLE
Code cleanup and deprecated API fixes

### PR DESCRIPTION
**Pull request by hrstoyanov**
@fdumay 
This is a pull request for:
 - Gradle deprecated APIs fixes
- General code clean up (as reported byIntelliJ).

This should close Issue #52

### CODE REVIEW

**Comment by hrstoyanov** [comment]
Has this been review Ed?

**Comment by fdumay** [comment]
I'm reviewing it. Nice job ;) thanks

**Comment by fdumay** [comment]
I published under the version 0.6.0 available on centrals (maven & gradle)

**Comment by hrstoyanov** [comment]
Thank you!

**Comment by hrstoyanov** [comment]
Thank you! Did you publish the latest 0.6 snapshot?

**Pull request merged**
